# -*- coding: utf-8 -*-
"""
Created on Sun Jul  8 13:50:54 2018

@author: LingXue
"""
import os
import shutil

word_to_pattern =  r'./data/word_to_pattern.txt'
word_dict = r'./data/Chinese_stopwords.txt'
sentence_word_q1 = r'./data/train_15_word_q1.txt'
sentence_word_q2 = r'./data/train_15_word_q2.txt'


def rm_stopwords(file_path, word_dict):
    """
        rm stop word for {file_path}, stop words save in {word_dict} file.
        file_path: file path of file generated by function splitwords.
                    each lines of file is contains many words ,each word separate from each other by space.
        word_dict: file containing stop words, and every stop words in one line.
        output: file_path which have been removed stop words and overwrite original file.
    """

    # 从文件中将停用词读取出来，并保存到字典stop_dict中
    stop_dict = {}
    with open(word_dict,'r', encoding='UTF-8') as d:
        for word in d:
            stop_dict[word.strip("\n")] = 1
    # 如果存在临时文件将其删除
    if os.path.exists(file_path + ".tmp"):
        os.remove(file_path + ".tmp")

    print ("now remove stop words in %s." % file_path)
    # 安行删除停用词
    with open(file_path,'r', encoding='UTF-8') as f1, open(file_path + ".tmp", "w", encoding='UTF-8') as f2:
        for line in f1:
            tmp_list = []  # 将非停用词保存下来
            words = line.split()
            print(line)
            for word in words:
                if word not in stop_dict:
                    tmp_list.append(word)
            words_without_stop = " ".join(tmp_list)
            to_write = words_without_stop + "\n"
            f2.write(to_write)
        f1.close()
        f2.close()
    # 将去除停用词的pattern文件重新到原路径
    shutil.move(file_path + ".tmp", file_path)
    print ("stop words in %s has been removed." % file_path)

rm_stopwords(sentence_word_q1, word_dict)

rm_stopwords(sentence_word_q2, word_dict)


print ("now combine two words ,one from setence one and another from setence two. and save in %s." %word_to_pattern)
#q1,q2 分词之后，分别两两组合，形成pattern   
with open(sentence_word_q1,"r",encoding ='utf-8')as f1,open(sentence_word_q2,'r',encoding = 'utf-8') as f2,open(word_to_pattern,'w',encoding='utf-8') as f3:
     line1 = f1.readline()
     line2 = f2.readline()
     
     while line1 and line2:
          temp=""
          for t in line1.split():
               for k in line2.split():
                 temp = temp+" "+t+k
          f3.write(temp+'\n')
          line1 = f1.readline()
          line2 = f2.readline()
     f1.close()
     f2.close()
     f3.close()
print("combine  words to pattern has  finished")